language: php

php:
  - "5.4"
  - "5.3"

before_script:
  - composer install
  - php tests/Functional/app/console doctrine:database:create
  - php tests/Functional/app/console doctrine:schema:update --force